### PR TITLE
Swapping kafka and rabbitmq examples

### PR DESCRIPTION
**Pull request by gaal-dev**
The author just mistyped therefore I swapped examples

"If you use the RabbitMQ binder, you can download http-transformer-with-RabbitMQ-binder After downloading and unpacking the source code, you can build the application by using Maven, as follows:

cd composed-http-transformer-kafka
./mvnw clean install

If you use the Kafka binder, you can download http-transformer-with-Kafka-binder After downloading and unpacking the source code, you can build the application by using Maven, as follows:

cd composed-http-transformer-rabbitmq
./mvnw clean install"

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
@gaal-dev Thanks for the fixes. Did you get the Contributor License Agreement notification? Once you sign it, we'll have this merged.

**Comment by gaal-dev** [comment]
> Did you get the Contributor License Agreement notification?

@ilayaperumalg  I am not sure. Where can I check it?

**Comment by pivotal-issuemaster** [comment]
@gaal-dev Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-io/dataflow.spring.io&pullRequestId=225) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gaal-dev Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/dataflow.spring.io&pullRequestId=225)!

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Pull request merged**
