### PR TITLE
Update 3-manual.md

### PR DESCRIPTION
**Pull request by thecoder8890**
Added the link for download spring cloud dataflow server local for manual installation

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@thecoder8890 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/dataflow.spring.io&pullRequestId=234)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-io/dataflow.spring.io&pullRequestId=234) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@thecoder8890 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/dataflow.spring.io&pullRequestId=234)!

**Comment by thecoder8890** [comment]
> @thecoder8890 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/dataflow.spring.io&pullRequestId=234)!
> 
> [Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-io/dataflow.spring.io&pullRequestId=234) to manually synchronize the status of this Pull Request.
> 
> See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

Done

**Comment by oodamien** [comment]
Thanks @thecoder8890

**Pull request merged**
