### PR TITLE
Fix minor typo in Spring Batch Jobs example

### PR DESCRIPTION
**Pull request by pavlosav**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pavlosav Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/dataflow.spring.io&pullRequestId=356)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-io/dataflow.spring.io&pullRequestId=356) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pavlosav** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@pavlosav This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by ilayaperumalg** [comment]
@pavlosav Thanks for the fix.

**Comment by ilayaperumalg** [comment]
Cherry-picked and pushed the changes into `main` as 8dd3757

**Pull request merged**
