### PR TITLE
Deprecate Helm Hub Chart

### PR DESCRIPTION
**Pull request by chrisjs**
Relates to: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4063

### CODE REVIEW

**Review by sabbyanandan — CHANGES_REQUESTED** [review]
LGTM. A few suggestions. 

1) I'd add a note stating that going forward (from 2.7.x.), we will not be maintaining the official Helm chart, and that the Bitnami is the preferred chart. Better to be more explicit about it. 

2) I'd cross-link to the Bitnami's issues page and encourage folks to report bugs and/or feature requests.

**Comment by chrisjs** [comment]
> LGTM. A few suggestions.
> 
> 1. I'd add a note stating that going forward (from 2.7.x.), we will not be maintaining the official Helm chart, and that the Bitnami is the preferred chart. Better to be more explicit about it.
> 2. I'd cross-link to the Bitnami's issues page and encourage folks to report bugs and/or feature requests.

@sabbyanandan updated -- copy/pasted the above for the most part. I used `2.6.1` rather than `2.7.x` given while `2.6.0` was the first in the `2.6.x` line, CTR was missing/broke in the chart, and `2.6.1` is the first in that line that passed the AT's.

let me know if other changes are needed or its good to merge

**Review by sabbyanandan — APPROVED** [review]
Let's go!

**Comment by chrisjs** [comment]
merged in 72503614f3960e1f4fcea299dd1b585bc1f1fbc3

**Pull request closed without merging**
