### PR TITLE
updating the milestone version and repo type

### PR DESCRIPTION
**Pull request by tech-tinvenc**
While trying to run the local setup, received 404 as the  repo type is snapshot.  trying to correct the version to get correct link

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@tech-tinvenc Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/dataflow.spring.io&pullRequestId=324)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-io/dataflow.spring.io&pullRequestId=324) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by ilayaperumalg** [comment]
Hi @tech-tinvenc , Thanks for PR! 

Given we have just released 2.7.0 release (on SCDF) and 2.6.0 (for Skipper), we don't keep the milestone versions in the documentations. The milestones and the snapshot versions are shown only for the upstream version which is now 2.8.0-SNAPSHOT and we haven't done a milestone on this version yet (we are just getting started there).

We recommend you try out the current which is 2.7.0.

Closing this PR as we won't be able to accept this but thanks for your interest in trying out.

**Comment by pivotal-issuemaster** [comment]
@tech-tinvenc Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-io/dataflow.spring.io&pullRequestId=324)!

**Comment by tech-tinvenc** [comment]
`wget https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-dataflow-server/2.7.0/spring-cloud-dataflow-server-2.7.0.jar
wget https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-dataflow-shell/2.7.0/spring-cloud-dataflow-shell-2.7.0.jar
`

These two wget urls are providing 404 when we are trying.

page: https://dataflow.spring.io/docs/installation/local/manual/

**Comment by ilayaperumalg** [comment]
I see what you mean. The fix on the repo type needs to be applied. I will push your change after removing the version change. Thanks again.

**Comment by tech-tinvenc** [comment]
I have noted that this will break the below snapshot section. We might need to include additional snapshot variables

**Comment by ilayaperumalg** [comment]
Thanks for catching this. I pushed your commit by changing the fix to use `release` since we need to keep **only** the release repositories in the branches apart from `master`: 47f2183

Will close this PR once the site is published with the changes.

**Comment by ilayaperumalg** [comment]
Fixed now: https://dataflow.spring.io/docs/installation/local/manual/

**Pull request closed without merging**
